---
- name: Listen for events on a webhook
  hosts: all

  sources:
   - ansible.eda.webhook:
       host: 0.0.0.0
       port: 5000

  rules:
    
   - name: Filter out the name of the system
     condition: event.payload is defined
     action:
        run_job_template:
          name: Filter_Regex
          organization: Default
          post_events: true


   - name: Restart apache on the server
     condition: event.server_name is defined
     action:
        run_job_template:
          name: Restart_Apache
          organization: Default
          job_args:
            extra_vars:
              my_payload: "{{ event.server_name }}"
