---
- name: Regex Processing for hostnames
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    eda_input: "{{ ansible_eda.event.payload }}"  # access event payload

  tasks:

    - name: Print out the payload
      ansible.builtin.debug:
        msg: "{{ eda_input }}"

    - name: Trying to set Artifacts
      ansible.builtin.set_stats:
        data:
          server_name: "{{ eda_input |  regex_replace('^.+:..', '') | regex_replace('down.+$', '')}}"
        per_host: no

    - name: Print server name
      ansible.builtin.debug: 
        msg: "{{ server_name }}"
